// Generated by CoffeeScript 1.3.3

describe('MainCtrl', function() {
  var ctrl, scope, _ref;
  _ref = [null, null], ctrl = _ref[0], scope = _ref[1];
  beforeEach(module('lol'));
  beforeEach(inject(function($controller, $rootScope) {
    scope = $rootScope.$new();
    return ctrl = $controller('MainCtrl', {
      $scope: scope
    });
  }));
  return it('modal should be hidden', function() {
    return expect(scope.visibleModal).toBeFalsy();
  });
});
