// Generated by CoffeeScript 1.6.2
describe('LOL testing directives', function() {
  beforeEach(module('lol'));
  describe('Stats testing', function() {
    var el, scope;

    scope = null;
    el = null;
    beforeEach(inject(function($rootScope, $compile, $controller) {
      var ctrl;

      el = angular.element("<stats></stats>");
      scope = $rootScope;
      ctrl = $controller('MainCtrl', {
        $scope: scope
      });
      $compile(el)(scope);
      return scope.$digest();
    }));
    it('should be 10 stats for character', function() {
      var lists;

      lists = el.find('li');
      return expect(lists.length).toBe(10);
    });
    return it('stats should be an Object with params', function() {
      return expect(scope.stats).toEqual(jasmine.any(Object));
    });
  });
  return describe('Items testing', function() {});
});
