// Generated by CoffeeScript 1.6.2
describe('filter', function() {
  beforeEach(module('lol'));
  return describe('interpolate', function() {
    return it('should run filter', function() {
      return expect(true).toBe(true);
    });
  });
});
