// Generated by CoffeeScript 1.3.3

describe('service', function() {
  beforeEach(module('lol'));
  return describe('version', function() {
    return it('should return current version', function() {
      return expect(true).toBe(true);
    });
  });
});
