$(function(){
    $.getScript('js/characters.js');
    $.getScript('js/skills.js');
    $.getScript('js/masteries.js');
    $.getScript('js/runes.js');
    $.getScript('js/spells.js');
    $.getScript('js/items.js');
    $.getScript('js/images.js');
    $.getScript('js/global.js');
    $.getScript('js/init-action.js');
    $.getScript('js/easyTooltip.js');
    $.getScript('js/init.js');
    $.getScript('js/tooltip-items.js');
    $.getScript('js/tooltip-masteries.js');
    $.getScript('js/tooltip-skills.js');
    $.getScript('js/tooltip-spells.js');
    $.getScript('js/tooltip-runes.js');
    $.getScript('js/bind.js');
});
