// Generated by CoffeeScript 1.6.1

LOL.directive('stats', function() {
  var directiveObj;
  return directiveObj = {
    template: "<ul><li ng-repeat='(key, val) in stats'>{{ key }} <span>{{ val }}</span></li></ul>",
    restrict: 'E',
    scope: '='
  };
});
