// Generated by CoffeeScript 1.3.3
(function() {
  var LOL;

  LOL = angular.module('lol', []);

  LOL.constant('block', $('#block'));

  $(function() {
    initActions(function() {
      initItemsAction();
      initSpellsAction();
      initSkillsAction();
      initRunesAction();
      initMasterAction();
      initMasteries();
      return null;
    });
    $('#myModal').modal('hide');
    $("#tabs").tabs();
    $('#tabs .menu a').bind('click', function() {
      $('.character').effect('slide', 800);
      initActions();
      return null;
    });
    return null;
  });

}).call(this);
