// Generated by CoffeeScript 1.6.1
var LOL;

LOL = angular.module('lol', [], function($routeProvider, $locationProvider) {
  $routeProvider.when('/', {
    redirectTo: '/ahri'
  });
  $routeProvider.when('/ahri', {
    controller: 'AhriCtrl'
  });
  $routeProvider.when('/akali', {
    controller: 'AkaliCtrl'
  });
  return $routeProvider.when('/alistar', {
    controller: 'AlistarCtrl'
  });
});
