// Generated by CoffeeScript 1.6.2
LOL.factory('localService', function() {
  return {
    set: function(n, m) {
      return localStorage.setItem(n, m);
    },
    get: function(n) {
      return localStorage.getItem(n);
    },
    del: function(n) {
      return localStorage.removeItem(n);
    },
    reset: function() {
      var error;

      try {
        localStorage.clear();
        return window.location.reload();
      } catch (_error) {
        error = _error;
        return alert("Не удалось очистить локальное хранилище: " + error);
      }
    }
  };
});
