// Generated by CoffeeScript 1.3.3

describe('Controllers', function() {
  return describe('MainCtrl', function() {
    var ctrl, scope, _ref;
    _ref = [null, null], scope = _ref.scope, ctrl = _ref.ctrl;
    beforeEach(angular.module('lol'));
    beforeEach(inject(function($rootScope, $controller) {
      scope = $rootScope.$new();
      return $controller('MainCtrl', {
        $scope: scope
      });
    }));
    return it('should be default route name is Ahri', function() {
      return expect(scope.name).toEqual('Ahri');
    });
  });
});
