// Generated by CoffeeScript 1.3.3

describe('directives', function() {
  beforeEach(angular.module('lol.directives'));
  return describe('app-version', function() {
    return it('should print current version', function() {
      module(function($provide) {
        return $provide.value('version', 'TEST_VER');
      });
      return inject(function($compile, $rootScope) {
        var element;
        element = $compile('<span app-version></span>')($rootScope);
        return expect(element.text()).toEqual('TEST_VER');
      });
    });
  });
});
