// Generated by CoffeeScript 1.3.3

describe('filter', function() {
  beforeEach(angular.module('lol.filters'));
  return describe('interpolate', function() {
    return it('should run filter', function() {
      return $filter('maxTo');
    });
  });
});
