// Generated by CoffeeScript 1.3.3

describe('service', function() {
  beforeEach(angular.module('lol.services'));
  return describe('version', function() {
    return it('should return current version', function() {
      return expect(version).toBeUndefined();
    });
  });
});
